package graphio

import (
	"encoding/json"
	"flag"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/jyang234/golang-code-graph/internal/render"
)

// updateGolden rebases the committed .callgraph.md views instead of asserting
// against them, the standard Go golden-file convention.
var updateGolden = flag.Bool("update", false, "rewrite the .callgraph.md mermaid goldens")

// callGraphGoldens are committed graph.json goldens whose human-readable flowchart
// view we ALSO commit, as a *.callgraph.md sibling — the static-graph analogue of
// the trace's *.flow.md. The .md is a pure, deterministic function of the committed
// .graph.json (itself the analyze-guarded golden, regenerated by
// testdata/groundwork/regen.sh and ratcheted by the section manifest), so this
// harness needs no toolchain run: it decodes the golden, renders, and diffs. The
// layering is deliberate — the .graph.json gate catches an analyzer shift, this gate
// catches a renderer shift, and neither can launder the other.
//
// The set is curated for review value: loansvc (the rich effect vocabulary),
// blindsvc (reflect/unsafe blind spots AND frontier markers — the honesty channel),
// obligsvc and layeredsvc (clean layered graphs), and impeachsvc (the missed-root
// fixture, whose DB DELETE is reachable in the graph but from no entrypoint).
var callGraphGoldens = []string{
	"../../../testdata/groundwork/goldens/loansvc.graph.json",
	"../../../testdata/groundwork/goldens/blindsvc.graph.json",
	"../../../testdata/groundwork/goldens/obligsvc.graph.json",
	"../../../testdata/groundwork/goldens/layeredsvc.graph.json",
	"../../../internal/impeach/testdata/impeachsvc.graph.json",
}

func TestCallGraphMermaidGoldens(t *testing.T) {
	for _, gj := range callGraphGoldens {
		name := strings.TrimSuffix(filepath.Base(gj), ".graph.json")
		t.Run(name, func(t *testing.T) {
			raw, err := os.ReadFile(gj)
			if err != nil {
				t.Fatalf("read graph golden: %v", err)
			}
			var g Graph
			if err := json.Unmarshal(raw, &g); err != nil {
				t.Fatalf("decode %s: %v", gj, err)
			}
			// MaxTier 2 mirrors the CLI default (`flowmap graph --mermaid` collapses
			// tier-3 plumbing), so the committed view is exactly what a reviewer sees.
			got := render.Fence(g.Mermaid(MermaidOptions{MaxTier: 2}))

			mdPath := strings.TrimSuffix(gj, ".graph.json") + ".callgraph.md"
			assertGolden(t, mdPath, got)
		})
	}
}

// assertGolden compares got against the committed golden at path, or rebases it
// under -update. It is the single golden lifecycle the call-graph, diff, and rooted
// views all go through, so every committed .md view rebases identically.
func assertGolden(t *testing.T, path, got string) {
	t.Helper()
	if *updateGolden {
		if err := os.WriteFile(path, []byte(got), 0o644); err != nil {
			t.Fatalf("write golden: %v", err)
		}
		return
	}
	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("missing golden %s; run `go test ./internal/static/graphio -update`: %v", path, err)
	}
	if string(want) != got {
		t.Errorf("%s is stale (run -update to rebase):\n%s", path, firstDiff(string(want), got))
	}
}

// firstDiff returns a compact line-oriented view of the first divergence between
// the committed golden and the freshly rendered view, so a stale-golden failure
// names the exact line rather than dumping both documents.
func firstDiff(want, got string) string {
	wl := strings.Split(want, "\n")
	gl := strings.Split(got, "\n")
	n := len(wl)
	if len(gl) > n {
		n = len(gl)
	}
	var b strings.Builder
	shown := 0
	for i := 0; i < n && shown < 20; i++ {
		var w, g string
		if i < len(wl) {
			w = wl[i]
		}
		if i < len(gl) {
			g = gl[i]
		}
		if w == g {
			continue
		}
		if i < len(wl) {
			b.WriteString("- " + w + "\n")
		}
		if i < len(gl) {
			b.WriteString("+ " + g + "\n")
		}
		shown++
	}
	if shown == 0 {
		b.WriteString("(differ only in trailing whitespace or line count)\n")
	}
	return b.String()
}
