package diagram

import (
	"errors"
	"strings"
	"testing"
)

// genFor builds a minimal generated document carrying the id's provenance marker.
func genFor(id, body string) string {
	return "flowchart LR\n" +
		"    %% generated by gen-diagram from " + id + "/diagram.json @ unstamped — do not hand-edit the core\n" +
		body
}

// TestCheckFencedMatch pins that a committed mermaid fence carrying the manifest's
// marker is selected and, when it matches, Check passes silently.
func TestCheckFencedMatch(t *testing.T) {
	out := genFor("MYID", "    A[\"x\"]\n")
	file := "# doc\n\n```mermaid\n" + out + "```\n\ntrailing prose\n"
	if err := Check([]byte(file), out, "MYID"); err != nil {
		t.Errorf("fenced match should pass: %v", err)
	}
}

// TestCheckWholeFileMatch pins that a file with NO mermaid fences is compared
// whole (a raw .mmd golden), trailing newline included.
func TestCheckWholeFileMatch(t *testing.T) {
	out := genFor("MYID", "    A[\"x\"]\n")
	if err := Check([]byte(out), out, "MYID"); err != nil {
		t.Errorf("whole-file match should pass: %v", err)
	}
}

// TestCheckDriftIsVerdict pins that a drifted block returns a Verdict (exit 1)
// naming the first differing line.
func TestCheckDriftIsVerdict(t *testing.T) {
	out := genFor("MYID", "    A[\"x\"]\n")
	stale := genFor("MYID", "    A[\"STALE\"]\n")
	file := "```mermaid\n" + stale + "```\n"
	err := Check([]byte(file), out, "MYID")
	var v Verdict
	if !errors.As(err, &v) {
		t.Fatalf("drift = %v (%T), want a Verdict", err, err)
	}
	if !strings.Contains(v.Msg, "line 3") {
		t.Errorf("drift message should name the first differing line (3): %q", v.Msg)
	}
}

// TestCheckBlockSelection pins the fail-closed selector: zero matching blocks and
// two matching blocks are BOTH operational errors (not verdicts).
func TestCheckBlockSelection(t *testing.T) {
	out := genFor("MYID", "    A[\"x\"]\n")

	// A mermaid fence exists, but it carries a DIFFERENT id's marker → 0 candidates.
	other := "```mermaid\n" + genFor("OTHER", "    A[\"x\"]\n") + "```\n"
	err := Check([]byte(other), out, "MYID")
	var v Verdict
	if err == nil || errors.As(err, &v) {
		t.Errorf("zero candidates = %v (%T), want a non-verdict error", err, err)
	}

	// Two blocks both carrying MYID's marker → ambiguous, ≥2 candidates.
	two := "```mermaid\n" + out + "```\n\n```mermaid\n" + out + "```\n"
	err = Check([]byte(two), out, "MYID")
	if err == nil || errors.As(err, &v) {
		t.Errorf("two candidates = %v (%T), want a non-verdict error", err, err)
	}
}
