package diagram

import (
	"fmt"
	"strings"
)

// Check gates a committed file against freshly generated output — the drift half
// of gen-diagram (regenerate-and-diff, tenet 5: the machine verifies its own
// invariant). manifestID is the diagram's id, used to select the right block.
//
// Selection is deterministic and fail-closed:
//   - If the file contains ANY ```mermaid fenced blocks, the candidate is the one
//     whose inner content carries the provenance marker "generated by gen-diagram
//     from <manifestID>/". EXACTLY one candidate must exist — 0 or ≥2 is an
//     operational error (a doc with no matching block, or two the id cannot
//     disambiguate). The compare is against that block's inner content.
//   - If the file contains NO mermaid fences at all, the whole file is compared
//     byte-for-byte (it must equal the generated output exactly, trailing newline
//     included).
//
// On a match Check returns nil (the caller prints nothing, exit 0). On drift it
// returns a Verdict naming the first differing line (exit 1). A block-selection
// failure is a plain error (exit 2).
//
// NOTE on "first line": the spec phrases selection as the block "whose first line
// contains" the marker, but the generated block's first line is `flowchart <dir>`
// and the marker rides the SECOND line (the `%%` provenance comment). Matching on
// "the block's inner content contains the marker" is the only reading that can
// ever select a well-formed block, and it is robust to the marker's line position.
func Check(fileContent []byte, generated, manifestID string) error {
	blocks := mermaidBlocks(string(fileContent))
	if len(blocks) == 0 {
		// No fences: the file IS the diagram. Byte-compare the whole thing.
		return compareLines(string(fileContent), generated, "file")
	}
	marker := "generated by gen-diagram from " + manifestID + "/"
	var candidates []string
	for _, blk := range blocks {
		if strings.Contains(blk, marker) {
			candidates = append(candidates, blk)
		}
	}
	if len(candidates) != 1 {
		return fmt.Errorf("--check: found %d mermaid block(s) carrying %q, want exactly 1 (0 = the diagram is missing; ≥2 = the id cannot disambiguate them)", len(candidates), marker)
	}
	return compareLines(candidates[0], generated, "block")
}

// mermaidBlocks returns the inner content (with a trailing newline, matching the
// generated shape) of every ```mermaid …``` fenced block in content. Fence lines
// are matched trimmed so leading indentation on a fence does not hide a block;
// the inner LINES are kept verbatim for a byte-exact compare.
func mermaidBlocks(content string) []string {
	lines := strings.Split(content, "\n")
	var blocks []string
	for i := 0; i < len(lines); i++ {
		if strings.TrimSpace(lines[i]) != "```mermaid" {
			continue
		}
		var inner []string
		j := i + 1
		for ; j < len(lines); j++ {
			if strings.TrimSpace(lines[j]) == "```" {
				break
			}
			inner = append(inner, lines[j])
		}
		blocks = append(blocks, strings.Join(inner, "\n")+"\n")
		i = j // resume after the closing fence
	}
	return blocks
}

// compareLines byte-compares committed against generated, returning nil on an
// exact match or a Verdict naming the first differing line (1-based). The message
// labels the two sides "committed" (what is in the file) and "generated" (what
// gen-diagram produces now) — unambiguous either way round, so a stale golden
// says exactly which line to fix.
func compareLines(committed, generated, what string) error {
	if committed == generated {
		return nil
	}
	cl := strings.Split(committed, "\n")
	gl := strings.Split(generated, "\n")
	n := len(cl)
	if len(gl) > n {
		n = len(gl)
	}
	for i := 0; i < n; i++ {
		cok, gok := i < len(cl), i < len(gl)
		var c, g string
		if cok {
			c = cl[i]
		}
		if gok {
			g = gl[i]
		}
		if c != g || cok != gok {
			return Verdict{Msg: fmt.Sprintf("--check: committed %s drifted from the generated core at line %d: committed %q, generated %q", what, i+1, c, g)}
		}
	}
	// The two strings differ but no line does — only possible on a trailing-newline
	// discrepancy the line split absorbed. Report it rather than pass silently.
	return Verdict{Msg: fmt.Sprintf("--check: committed %s differs from the generated core in trailing content", what)}
}
