package diagram

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/jyang234/golang-code-graph/internal/groundwork/graph"
)

// testGraph is a small hand-built graph exercising every feature a diagram needs:
// pointer-receiver methods, a value/pointer Score twin (ambiguity), a boundary
// pseudo-node endpoint (drawable as a core node), a DUPLICATE (from,to) pair
// carried twice under different modes (the unique-pair dedup), and a genuine
// self-edge (a self-loop core edge).
func testGraph() *graph.Graph {
	return &graph.Graph{
		Nodes: []graph.Node{
			{FQN: "(*svc/handler.App).Create", Tier: 1},
			{FQN: "(*svc/repo.Store).Save", Tier: 2},
			{FQN: "(*svc/repo.Store).Load", Tier: 2},
			{FQN: "svc/scoring.Score", Tier: 2},
			{FQN: "(*svc/scoring.Remote).Score", Tier: 3},
			{FQN: "(*svc/worker.Loop).Run", Tier: 1},
		},
		Edges: []graph.Edge{
			{From: "(*svc/handler.App).Create", To: "(*svc/repo.Store).Save", Tier: 2},
			// Same pair, concurrent mode: a distinct RECORD, one unique PAIR.
			{From: "(*svc/handler.App).Create", To: "(*svc/repo.Store).Save", Tier: 2, Concurrent: true},
			{From: "(*svc/handler.App).Create", To: "boundary:db QueryContext", Tier: 1, Boundary: "db"},
			{From: "(*svc/repo.Store).Save", To: "boundary:db INSERT rows", Tier: 1, Boundary: "outbound-sync"},
			{From: "(*svc/worker.Loop).Run", To: "(*svc/worker.Loop).Run", Tier: 1}, // self-loop
		},
	}
}

func oneGraph(g *graph.Graph) map[string]*graph.Graph { return map[string]*graph.Graph{"g": g} }

func gen(t *testing.T, m *Manifest, graphs map[string]*graph.Graph) string {
	t.Helper()
	out, err := Generate(m, graphs)
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	return out
}

func node(id, fn, label string) ManifestNode {
	return ManifestNode{ID: id, Graph: "g", Fn: fn, Label: label}
}

// TestCoreEdgesInduced pins the induced-subgraph rule: a present pair is drawn, an
// absent pair is not, a self-edge is drawn as a self-loop, and NOTHING but a graph
// edge produces a solid arrow. It is a byte-exact pin over a subgraph-free,
// overlay-free manifest so both the edge SET and the emission ORDER are enforced.
func TestCoreEdgesInduced(t *testing.T) {
	m := &Manifest{
		ID: "CORE-TEST", Direction: "LR",
		Nodes: []ManifestNode{
			node("A", "handler.App).Create", "Create"),
			node("B", "repo.Store).Save", "Save"),
			node("C", "repo.Store).Load", "Load"),
			node("DB", "boundary:db QueryContext", "db QueryContext"),
			node("LP", "worker.Loop).Run", "Loop.Run"),
		},
	}
	want := "flowchart LR\n" +
		"    %% generated by gen-diagram from CORE-TEST/diagram.json @ unstamped — do not hand-edit the core\n" +
		"    A[\"Create\"] --> B[\"Save\"]\n" + // present pair drawn
		"    A --> DB[\"db QueryContext\"]\n" + // boundary pseudo-node as a core node
		"    LP[\"Loop.Run\"] --> LP\n" + // self-loop drawn
		"    C[\"Load\"]\n" // no core edge touches C → standalone (absent pairs not drawn)
	if got := gen(t, m, oneGraph(testGraph())); got != want {
		t.Errorf("core induction:\n got:\n%s\nwant:\n%s", got, want)
	}
}

// TestCrossGraphNeverDrawn pins that an edge existing in BOTH graphs is still not
// drawn between two nodes bound to DIFFERENT logical graphs — a diagram edge is a
// single-graph fact.
func TestCrossGraphNeverDrawn(t *testing.T) {
	g1 := &graph.Graph{
		Nodes: []graph.Node{{FQN: "svc/a.X", Tier: 1}, {FQN: "svc/a.Y", Tier: 1}},
		Edges: []graph.Edge{{From: "svc/a.X", To: "svc/a.Y", Tier: 1}},
	}
	g2 := &graph.Graph{
		Nodes: []graph.Node{{FQN: "svc/a.X", Tier: 1}, {FQN: "svc/a.Y", Tier: 1}},
		Edges: []graph.Edge{{From: "svc/a.X", To: "svc/a.Y", Tier: 1}},
	}
	m := &Manifest{
		ID: "X", Direction: "LR",
		Nodes: []ManifestNode{
			{ID: "NA", Graph: "one", Fn: "a.X", Label: "X"},
			{ID: "NB", Graph: "two", Fn: "a.Y", Label: "Y"},
		},
	}
	out := gen(t, m, map[string]*graph.Graph{"one": g1, "two": g2})
	if strings.Contains(out, "-->") {
		t.Errorf("cross-graph pair must not draw a solid edge:\n%s", out)
	}
}

// TestTiersAnnotation pins the ` (tN)` suffix read from the graph, including the
// boundary-endpoint-no-tier honesty case: a resolved boundary pseudo-node has no
// tier, so it gets no suffix (never a fabricated one).
func TestTiersAnnotation(t *testing.T) {
	m := &Manifest{
		ID: "T", Direction: "LR", Tiers: true,
		Nodes: []ManifestNode{
			node("A", "handler.App).Create", "Create"),                // tier 1
			node("S", "scoring.Remote).Score", "Score"),               // tier 3
			node("DB", "boundary:db QueryContext", "db QueryContext"), // no tier
		},
	}
	out := gen(t, m, oneGraph(testGraph()))
	for _, want := range []string{`A["Create (t1)"]`, `S["Score (t3)"]`, `DB["db QueryContext"]`} {
		if !strings.Contains(out, want) {
			t.Errorf("tiers output missing %q:\n%s", want, out)
		}
	}
	// The boundary node must carry NO tier suffix (honest omission).
	if strings.Contains(out, "db QueryContext (t") {
		t.Errorf("boundary pseudo-node must not get a tier suffix:\n%s", out)
	}
}

// TestTiersAmbiguousAbstains pins that a node the graph carries at two tiers makes
// a tiers:true diagram ABSTAIN (error), never annotate an arbitrary tier.
func TestTiersAmbiguousAbstains(t *testing.T) {
	g := &graph.Graph{Nodes: []graph.Node{
		{FQN: "svc/gen.F[int]", Tier: 1},
		{FQN: "svc/gen.F[int]", Tier: 3}, // same display FQN, different tier
	}}
	m := &Manifest{
		ID: "T", Direction: "LR", Tiers: true,
		Nodes: []ManifestNode{node("A", "gen.F[int]", "F")},
	}
	_, err := Generate(m, oneGraph(g))
	if err == nil || !strings.Contains(err.Error(), "ambiguous") {
		t.Errorf("ambiguous-tier node under tiers:true = %v, want an abstain error", err)
	}
}

// TestOverlayNodeShapes pins every overlay-node shape declaration, including the
// empty-circle form. An all-overlay manifest needs no graph (and refers to none).
func TestOverlayNodeShapes(t *testing.T) {
	m := &Manifest{
		ID: "SHAPES", Direction: "LR",
		Overlays: Overlays{Nodes: []OverlayNode{
			{ID: "RECT", Label: "rect node", Shape: "rect"},
			{ID: "IMPL", Label: "implicit"}, // empty shape = rect
			{ID: "DB", Label: "db node", Shape: "db"},
			{ID: "CIRC", Label: "circle", Shape: "circle"},
			{ID: "EMPTY", Shape: "circle"}, // empty label, legal only for circle
		}},
	}
	out := gen(t, m, map[string]*graph.Graph{})
	for _, want := range []string{
		`RECT["rect node"]`,
		`IMPL["implicit"]`,
		`DB[("db node")]`,
		`CIRC(("circle"))`,
		`EMPTY(( ))`,
	} {
		if !strings.Contains(out, want) {
			t.Errorf("overlay shapes missing %q:\n%s", want, out)
		}
	}
}

// TestOverlayEmptyLabelRules pins that an empty label is legal ONLY with a circle:
// rect/db with an empty label, and an unknown shape, are errors (fail closed).
func TestOverlayEmptyLabelRules(t *testing.T) {
	empty := func(shape string) error {
		_, err := Generate(&Manifest{
			ID: "X", Direction: "LR",
			Overlays: Overlays{Nodes: []OverlayNode{{ID: "N", Shape: shape}}},
		}, map[string]*graph.Graph{})
		return err
	}
	if err := empty("rect"); err == nil {
		t.Error("empty-label rect overlay node must error")
	}
	if err := empty("db"); err == nil {
		t.Error("empty-label db overlay node must error")
	}
	if err := empty(""); err == nil {
		t.Error("empty-label default-shape overlay node must error")
	}
	// Unknown shape is an error.
	_, err := Generate(&Manifest{
		ID: "X", Direction: "LR",
		Overlays: Overlays{Nodes: []OverlayNode{{ID: "N", Label: "x", Shape: "hexagon"}}},
	}, map[string]*graph.Graph{})
	if err == nil || !strings.Contains(err.Error(), "unknown shape") {
		t.Errorf("unknown overlay shape = %v, want an unknown-shape error", err)
	}
}

// TestOverlayGuardTrips pins the core invariant: an overlay edge whose endpoints
// both resolve to same-graph manifest nodes and whose (fqn,fqn) pair EXISTS in the
// graph is a VERDICT — judgment may not dash-draw a computed fact.
func TestOverlayGuardTrips(t *testing.T) {
	m := &Manifest{
		ID: "X", Direction: "LR",
		Nodes: []ManifestNode{
			node("A", "handler.App).Create", "Create"),
			node("B", "repo.Store).Save", "Save"),
		},
		Overlays: Overlays{Edges: []OverlayEdge{{From: "A", To: "B", Label: "FIX"}}},
	}
	_, err := Generate(m, oneGraph(testGraph()))
	var v Verdict
	if !errors.As(err, &v) {
		t.Fatalf("overlay restating a core edge = %v (%T), want a Verdict", err, err)
	}
	if !strings.Contains(v.Msg, "restates a core edge") {
		t.Errorf("guard message = %q, want it to name the restated edge", v.Msg)
	}
}

// TestOverlayGuardExempt pins the two exemptions: an overlay edge touching an
// OVERLAY node, and one SPANNING two graphs (even when the edge exists in each),
// cannot restate a single-graph core edge and so do not trip the guard.
func TestOverlayGuardExempt(t *testing.T) {
	// (1) Overlay-node endpoint: A -.-> OV is exempt even though A→Save is a core edge.
	m := &Manifest{
		ID: "X", Direction: "LR",
		Nodes: []ManifestNode{node("A", "handler.App).Create", "Create")},
		Overlays: Overlays{
			Nodes: []OverlayNode{{ID: "OV", Label: "concept"}},
			Edges: []OverlayEdge{{From: "A", To: "OV"}},
		},
	}
	if _, err := Generate(m, oneGraph(testGraph())); err != nil {
		t.Errorf("overlay edge to an overlay node must be exempt: %v", err)
	}

	// (2) Cross-graph: X→Y exists in BOTH graphs, but NA(g1)→NB(g2) spans graphs → exempt.
	g := &graph.Graph{
		Nodes: []graph.Node{{FQN: "svc/a.X", Tier: 1}, {FQN: "svc/a.Y", Tier: 1}},
		Edges: []graph.Edge{{From: "svc/a.X", To: "svc/a.Y", Tier: 1}},
	}
	m2 := &Manifest{
		ID: "X", Direction: "LR",
		Nodes: []ManifestNode{
			{ID: "NA", Graph: "one", Fn: "a.X", Label: "X"},
			{ID: "NB", Graph: "two", Fn: "a.Y", Label: "Y"},
		},
		Overlays: Overlays{Edges: []OverlayEdge{{From: "NA", To: "NB", Label: "FIX"}}},
	}
	g2 := &graph.Graph{
		Nodes: []graph.Node{{FQN: "svc/a.X", Tier: 1}, {FQN: "svc/a.Y", Tier: 1}},
		Edges: []graph.Edge{{From: "svc/a.X", To: "svc/a.Y", Tier: 1}},
	}
	if _, err := Generate(m2, map[string]*graph.Graph{"one": g, "two": g2}); err != nil {
		t.Errorf("cross-graph overlay edge must be exempt: %v", err)
	}
}

// TestResolveErrors pins the three fail-closed resolution refusals, each deferring
// to fqnres' shared wording: UNRESOLVED, AMBIGUOUS, and the regex-form rejection
// (a diagram node names exactly one function).
func TestResolveErrors(t *testing.T) {
	try := func(fn string) error {
		_, err := Generate(&Manifest{
			ID: "X", Direction: "LR",
			Nodes: []ManifestNode{node("A", fn, "L")},
		}, oneGraph(testGraph()))
		return err
	}
	if err := try("does.Not.Exist"); err == nil || !strings.Contains(err.Error(), "UNRESOLVED") {
		t.Errorf("unresolved fn = %v, want UNRESOLVED", err)
	}
	if err := try(".Score"); err == nil || !strings.Contains(err.Error(), "AMBIGUOUS") {
		t.Errorf("ambiguous fn = %v, want AMBIGUOUS", err)
	}
	if err := try("/Score/"); err == nil || !strings.Contains(err.Error(), "regex") {
		t.Errorf("regex fn = %v, want a regex-rejection error", err)
	}
}

// TestDuplicateFQNRejected pins that two manifest nodes on the same graph resolving
// to one FQN is an error — one function drawn as two ids is an ambiguous diagram.
func TestDuplicateFQNRejected(t *testing.T) {
	m := &Manifest{
		ID: "X", Direction: "LR",
		Nodes: []ManifestNode{
			node("A", "handler.App).Create", "Create"),
			node("A2", "App).Create", "Create again"), // same resolved FQN
		},
	}
	_, err := Generate(m, oneGraph(testGraph()))
	if err == nil || !strings.Contains(err.Error(), "resolve to") {
		t.Errorf("duplicate-fqn = %v, want an ambiguous-diagram error", err)
	}
}

// TestIDValidation pins the mermaid-identifier charset, the single id namespace
// (node/overlay/subgraph collide), a dangling subgraph member, a dangling overlay
// endpoint, and a node placed in two subgraphs.
func TestIDValidation(t *testing.T) {
	base := func() *Manifest {
		return &Manifest{ID: "X", Direction: "LR", Nodes: []ManifestNode{node("A", "handler.App).Create", "Create")}}
	}
	// Bad charset on a node id.
	m := base()
	m.Nodes[0].ID = "bad-id"
	if _, err := Generate(m, oneGraph(testGraph())); err == nil || !strings.Contains(err.Error(), "valid mermaid identifier") {
		t.Errorf("bad id charset = %v, want an identifier error", err)
	}
	// Duplicate id across node + overlay node.
	m = base()
	m.Overlays = Overlays{Nodes: []OverlayNode{{ID: "A", Label: "dup"}}}
	if _, err := Generate(m, oneGraph(testGraph())); err == nil || !strings.Contains(err.Error(), "duplicate id") {
		t.Errorf("duplicate id = %v, want a duplicate-id error", err)
	}
	// Subgraph member that is not a manifest node.
	m = base()
	m.Subgraphs = []Subgraph{{ID: "S", Nodes: []string{"NOPE"}}}
	if _, err := Generate(m, oneGraph(testGraph())); err == nil || !strings.Contains(err.Error(), "not a manifest node id") {
		t.Errorf("dangling subgraph member = %v, want a dangling-member error", err)
	}
	// Overlay edge endpoint that references nothing.
	m = base()
	m.Overlays = Overlays{Edges: []OverlayEdge{{From: "A", To: "NOPE"}}}
	if _, err := Generate(m, oneGraph(testGraph())); err == nil || !strings.Contains(err.Error(), "not a manifest node or overlay node id") {
		t.Errorf("dangling overlay endpoint = %v, want an unknown-endpoint error", err)
	}
	// A SUBGRAPH id is a registered id but has no node declaration, so it cannot be
	// an overlay edge endpoint (else it would emit a broken empty endpoint).
	m = base()
	m.Subgraphs = []Subgraph{{ID: "S", Nodes: []string{"A"}}}
	m.Overlays = Overlays{Nodes: []OverlayNode{{ID: "OV", Label: "x"}}, Edges: []OverlayEdge{{From: "S", To: "OV"}}}
	if _, err := Generate(m, oneGraph(testGraph())); err == nil || !strings.Contains(err.Error(), "not a manifest node or overlay node id") {
		t.Errorf("subgraph-id overlay endpoint = %v, want a rejection", err)
	}
	// A node in two subgraphs.
	m = base()
	m.Subgraphs = []Subgraph{{ID: "S1", Nodes: []string{"A"}}, {ID: "S2", Nodes: []string{"A"}}}
	if _, err := Generate(m, oneGraph(testGraph())); err == nil || !strings.Contains(err.Error(), "two subgraphs") {
		t.Errorf("node in two subgraphs = %v, want a two-subgraphs error", err)
	}
}

// TestGraphBindingErrors pins that a node binding an unknown logical graph, and a
// supplied graph referenced by no node, are both errors (fail closed).
func TestGraphBindingErrors(t *testing.T) {
	// Unknown logical graph.
	m := &Manifest{ID: "X", Direction: "LR", Nodes: []ManifestNode{{ID: "A", Graph: "missing", Fn: "handler.App).Create", Label: "L"}}}
	if _, err := Generate(m, oneGraph(testGraph())); err == nil || !strings.Contains(err.Error(), "unknown logical graph") {
		t.Errorf("unknown logical graph = %v, want an unknown-graph error", err)
	}
	// A supplied graph no node references.
	m = &Manifest{ID: "X", Direction: "LR", Nodes: []ManifestNode{node("A", "handler.App).Create", "L")}}
	graphs := map[string]*graph.Graph{"g": testGraph(), "extra": testGraph()}
	if _, err := Generate(m, graphs); err == nil || !strings.Contains(err.Error(), "referenced by no manifest node") {
		t.Errorf("unreferenced supplied graph = %v, want an unreferenced-graph error", err)
	}
}

// TestSubgraphEmission pins the block shape byte-for-byte: intra-subgraph core
// edges and undeclared members are declared INSIDE the block (8-space indent), a
// cross-subgraph edge is emitted OUTSIDE it, and the member with no intra edge is
// still declared in the block.
func TestSubgraphEmission(t *testing.T) {
	m := &Manifest{
		ID: "SG-TEST", Direction: "LR",
		Nodes: []ManifestNode{
			node("A", "handler.App).Create", "Create"),
			node("B", "repo.Store).Save", "Save"),
			node("C", "repo.Store).Load", "Load"),
			node("DB", "boundary:db QueryContext", "db QueryContext"),
		},
		Subgraphs: []Subgraph{{ID: "store", Title: "store [computed]", Nodes: []string{"A", "B", "C"}}},
	}
	want := "flowchart LR\n" +
		"    %% generated by gen-diagram from SG-TEST/diagram.json @ unstamped — do not hand-edit the core\n" +
		"    subgraph store[\"store [computed]\"]\n" +
		"        A[\"Create\"] --> B[\"Save\"]\n" + // intra edge, inside the block
		"        C[\"Load\"]\n" + // undeclared member, inside the block
		"    end\n" +
		"    A --> DB[\"db QueryContext\"]\n" // cross edge (member → non-member), outside
	if got := gen(t, m, oneGraph(testGraph())); got != want {
		t.Errorf("subgraph emission:\n got:\n%s\nwant:\n%s", got, want)
	}
}

// TestDeclarationExactlyOnce pins that a node referenced by several edges gets its
// bracket declaration exactly once, at first mention; later mentions are bare.
func TestDeclarationExactlyOnce(t *testing.T) {
	m := &Manifest{
		ID: "X", Direction: "LR",
		Nodes: []ManifestNode{
			node("A", "handler.App).Create", "Create"),
			node("B", "repo.Store).Save", "Save"),
			node("DB", "boundary:db QueryContext", "db QueryContext"),
		},
		Overlays: Overlays{
			Nodes: []OverlayNode{{ID: "OV", Label: "concept"}},
			Edges: []OverlayEdge{{From: "A", To: "OV", Label: "note"}},
		},
	}
	out := gen(t, m, oneGraph(testGraph()))
	// A participates in A→B, A→DB, and A -.-> OV, but is declared once.
	if n := strings.Count(out, `A["Create"]`); n != 1 {
		t.Errorf("A declared %d times, want exactly 1:\n%s", n, out)
	}
	if !strings.Contains(out, "    A --> DB[\"db QueryContext\"]") || !strings.Contains(out, "    A -.->|\"note\"| OV[\"concept\"]") {
		t.Errorf("later mentions of A should be bare:\n%s", out)
	}
}

// TestLabelEscaping pins the one deterministic label escape: an embedded double
// quote becomes &quot; (mermaid entity form), in both a node label and an edge label.
func TestLabelEscaping(t *testing.T) {
	m := &Manifest{
		ID: "X", Direction: "LR",
		Nodes: []ManifestNode{node("A", "handler.App).Create", `a "quoted" label`)},
		Overlays: Overlays{
			Nodes: []OverlayNode{{ID: "OV", Label: "concept"}},
			Edges: []OverlayEdge{{From: "A", To: "OV", Label: `say "hi"`}},
		},
	}
	out := gen(t, m, oneGraph(testGraph()))
	if !strings.Contains(out, `A["a &quot;quoted&quot; label"]`) {
		t.Errorf("node label quote not escaped:\n%s", out)
	}
	if !strings.Contains(out, `-.->|"say &quot;hi&quot;"|`) {
		t.Errorf("edge label quote not escaped:\n%s", out)
	}
}

// TestStampsLine pins the provenance stamp: the sorted-unique non-empty tool
// values of the input graphs, and the "unstamped" fallback when none carry one.
func TestStampsLine(t *testing.T) {
	// Two graphs, tools out of order + a duplicate → sorted unique.
	g1 := &graph.Graph{Tool: "z-tool", Nodes: []graph.Node{{FQN: "svc/a.X", Tier: 1}}}
	g2 := &graph.Graph{Tool: "a-tool", Nodes: []graph.Node{{FQN: "svc/b.Y", Tier: 1}}}
	m := &Manifest{ID: "X", Direction: "LR", Nodes: []ManifestNode{
		{ID: "NA", Graph: "one", Fn: "a.X", Label: "X"},
		{ID: "NB", Graph: "two", Fn: "b.Y", Label: "Y"},
	}}
	out := gen(t, m, map[string]*graph.Graph{"one": g1, "two": g2})
	if !strings.Contains(out, "@ a-tool, z-tool — do not hand-edit the core") {
		t.Errorf("multi-graph stamps not sorted-unique:\n%s", out)
	}
	// No tool anywhere → unstamped.
	out = gen(t, &Manifest{ID: "X", Direction: "LR", Nodes: []ManifestNode{node("A", "handler.App).Create", "L")}}, oneGraph(testGraph()))
	if !strings.Contains(out, "@ unstamped — do not hand-edit the core") {
		t.Errorf("no-tool stamps not 'unstamped':\n%s", out)
	}
}

// TestDeterministicOverShuffledInput pins that the diagram is a pure function of
// graph CONTENT, not node/edge arrival order — reversing both slices yields
// byte-identical output. Exercises subgraph, overlay, boundary node, and self-loop.
func TestDeterministicOverShuffledInput(t *testing.T) {
	m := &Manifest{
		ID: "D", Direction: "LR",
		Nodes: []ManifestNode{
			node("A", "handler.App).Create", "Create"),
			node("B", "repo.Store).Save", "Save"),
			node("DB", "boundary:db QueryContext", "db QueryContext"),
			node("LP", "worker.Loop).Run", "Loop.Run"),
		},
		Subgraphs: []Subgraph{{ID: "app", Title: "app", Nodes: []string{"A", "B"}}},
		Overlays: Overlays{
			Nodes: []OverlayNode{{ID: "OV", Label: "planned", Shape: "db"}},
			Edges: []OverlayEdge{{From: "B", To: "OV", Label: "FIX"}},
		},
	}
	a := gen(t, m, oneGraph(testGraph()))
	b := gen(t, m, oneGraph(reversed(testGraph())))
	if a != b {
		t.Errorf("output not deterministic across input order:\n%s\n---\n%s", a, b)
	}
}

func reversed(g *graph.Graph) *graph.Graph {
	c := *g
	c.Nodes = append([]graph.Node(nil), g.Nodes...)
	c.Edges = append([]graph.Edge(nil), g.Edges...)
	for i, j := 0, len(c.Nodes)-1; i < j; i, j = i+1, j-1 {
		c.Nodes[i], c.Nodes[j] = c.Nodes[j], c.Nodes[i]
	}
	for i, j := 0, len(c.Edges)-1; i < j; i, j = i+1, j-1 {
		c.Edges[i], c.Edges[j] = c.Edges[j], c.Edges[i]
	}
	return &c
}

// TestDirectionValidation pins that an empty/missing direction and an invalid one
// are both errors (fail closed — no silent default).
func TestDirectionValidation(t *testing.T) {
	mk := func(dir string) error {
		_, err := Generate(&Manifest{ID: "X", Direction: dir, Nodes: []ManifestNode{node("A", "handler.App).Create", "L")}}, oneGraph(testGraph()))
		return err
	}
	if err := mk(""); err == nil || !strings.Contains(err.Error(), "requires a direction") {
		t.Errorf("empty direction = %v, want a requires-direction error", err)
	}
	if err := mk("XX"); err == nil || !strings.Contains(err.Error(), "invalid direction") {
		t.Errorf("invalid direction = %v, want an invalid-direction error", err)
	}
}

// TestManifestIDRequired pins that a manifest with no id is refused (the id rides
// the provenance line and the --check selector).
func TestManifestIDRequired(t *testing.T) {
	_, err := Generate(&Manifest{Direction: "LR", Nodes: []ManifestNode{node("A", "handler.App).Create", "L")}}, oneGraph(testGraph()))
	if err == nil || !strings.Contains(err.Error(), "non-empty id") {
		t.Errorf("empty manifest id = %v, want a requires-id error", err)
	}
}

// TestLoadFileStrict pins the fail-closed decode: an unknown key and trailing data
// both error, while a well-formed manifest loads (parity with graph.Load).
func TestLoadFileStrict(t *testing.T) {
	write := func(s string) string {
		p := filepath.Join(t.TempDir(), "m.json")
		if err := os.WriteFile(p, []byte(s), 0o644); err != nil {
			t.Fatal(err)
		}
		return p
	}
	if _, err := LoadFile(write(`{"id":"X","direction":"LR","bogus":1,"nodes":[]}`)); err == nil {
		t.Error("unknown field must fail strict decode")
	}
	if _, err := LoadFile(write(`{"id":"X","direction":"LR","nodes":[]} trailing`)); err == nil {
		t.Error("trailing data after manifest JSON must error")
	}
	m, err := LoadFile(write(`{"id":"X","direction":"LR","nodes":[{"id":"A","graph":"g","fn":"f","label":"L"}]}`))
	if err != nil || m.ID != "X" || len(m.Nodes) != 1 {
		t.Errorf("valid manifest: m=%+v err=%v", m, err)
	}
}
