// Package diagram turns a hand-authored diagram manifest plus one or more
// flowmap graphs into a mermaid `flowchart` whose every SOLID edge is an
// induced-subgraph edge READ from a graph and whose every tier annotation is
// READ from a graph — neither can be typed by hand. The judgment content a human
// adds (proposed FIX edges, conceptual nodes) is declared in the manifest and
// always rendered DASHED, so a reader can tell the two apart at a glance and CI
// can gate the computed half against drift.
//
// Where `groundwork assert` verifies that a graph matches a doc's textual claims,
// `gen-diagram` produces the doc's *picture* from the graph: the boxes-and-arrows
// a human would otherwise draw from memory (and get wrong) become a deterministic
// function of (manifest, graphs). The manifest chooses WHICH functions to show
// and how to lay them out; the graph decides which arrows between them are real.
//
// # Counting basis
//
// A core edge exists between two manifest nodes iff the ordered pair of their
// resolved FQNs is present in the bound graph's set of UNIQUE (from, to) pairs —
// the same mode-blind basis the claims lens counts on (edges[] can carry a pair
// more than once; a plain call and a `go`-launched call are two records, one
// pair). Collapsing to unique pairs is what makes a drawn edge reproducible and
// mode-independent (pinned by TestCoreEdgesInduced).
//
// # Resolution — defer to fqnres (one source of truth)
//
// Each manifest node's `fn` is resolved against the graph it is bound to using
// internal/fqnres, the ONE name resolver `groundwork assert` and `flowmap graph
// --focus` also use, over the SAME universe the claims lens resolves an endpoint
// against: node FQNs ∪ every edge endpoint string (claims.EndpointUniverse), so a
// `boundary:*` pseudo-endpoint is drawable as a core node. A diagram node names
// exactly ONE function, so a `fn` must resolve to exactly one FQN: zero →
// UNRESOLVED error (fqnres.UnresolvedDetail), two or more → AMBIGUOUS error
// (fqnres.AmbiguousDetail). The `/regex/` form is meaningful only where multi-
// match is legal (a claim endpoint, a focus set); a single diagram node is not
// such a place, so a regex-form `fn` is refused outright (fail closed, tenet 2 —
// pinned by TestResolveErrors). A resolved endpoint that is not a graph NODE (a
// boundary pseudo-node) genuinely has no tier, so under `tiers: true` it simply
// gets no ` (tN)` suffix — an honest omission, not a fabricated tier
// (TestTiersAnnotation).
//
// # The overlay guard — judgment may never restate a computed fact
//
// An overlay (dashed) edge is a human's proposal: an arrow the graph does NOT
// have. If an overlay edge's two endpoints both resolve to manifest nodes bound
// to the SAME graph and that (fqn, fqn) pair EXISTS in the graph, the overlay is
// restating a fact the solid layer already draws — the dashed "proposal" is
// really the computed truth wearing a costume. That is refused as a VERDICT
// error (the graph now contradicts the manifest's judgment; CI must surface it —
// TestOverlayGuardTrips). Overlay edges that touch an overlay node, or that span
// two graphs, are exempt: they cannot restate a single-graph core edge
// (TestOverlayGuardExempt).
//
// # Emission order (byte-exact, deterministic)
//
//	flowchart <direction>
//	    %% generated by gen-diagram from <id>/diagram.json @ <stamps> — do not hand-edit the core
//	    <subgraph blocks, in manifest order — intra-subgraph core edges then undeclared members, all inside the block>
//	    <remaining core edges — spanning subgraphs or touching a non-member>
//	    <never-referenced manifest nodes — no core edge, not in a subgraph>
//	    <overlay edges, in manifest order — always dashed>
//	    <overlay nodes never touched by an overlay edge>
//
// Every ordering resolves to manifest order or a sort on the intrinsic (from
// index, to index) of the induced edges — never map iteration, arrival order, or
// a wall clock. A node's bracket declaration is emitted exactly once, at first
// mention; later mentions are the bare id (TestDeclarationExactlyOnce). A subgraph
// member's declaration MUST fall inside its block, because mermaid decides
// membership by declaration position. `<stamps>` is the sorted unique non-empty
// `tool` values of the input graphs, or the literal `unstamped` when the goldens
// strip it (TestStampsLine). The whole output is a pure function of (manifest,
// graphs): reversing a graph's node/edge slices yields byte-identical output
// (TestDeterministicOverShuffledInput).
//
// # Error style and fail-closed posture
//
// Every ambiguous, incomplete, or self-contradictory input is refused, never
// guessed: an unknown manifest key (DisallowUnknownFields), trailing data after
// the JSON value, an unresolved/ambiguous/regex `fn`, an id that is not a mermaid
// identifier, a duplicate id, a dangling subgraph/overlay reference, an unknown or
// unreferenced logical graph, an empty direction — all are errors. Only two error
// classes are VERDICTS (Verdict, mapped to groundwork's exit 1): the overlay guard
// tripping and a `--check` drift. Everything else is operational (exit 2).
package diagram

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"regexp"
	"sort"
	"strings"

	"github.com/jyang234/golang-code-graph/internal/fqnres"
	"github.com/jyang234/golang-code-graph/internal/groundwork/claims"
	"github.com/jyang234/golang-code-graph/internal/groundwork/graph"
	"github.com/jyang234/golang-code-graph/internal/groundwork/setutil"
)

// Manifest is a decoded diagram manifest: the human-authored half of the diagram
// (which functions to show, how to lay them out, what judgment to overlay). The
// graph-derived half — which solid edges exist, what tier each node is — is never
// in here; it is read from the graphs at generation time.
type Manifest struct {
	// ID names the diagram (e.g. "CG-6"). It rides the provenance comment and is
	// the token `--check` selects a committed block by. It is NOT a mermaid
	// identifier (it may carry '-'), so the identifier charset does not apply to it.
	ID string `json:"id"`
	// Direction is the flowchart direction, one of LR/RL/TB/BT/TD. Empty is an
	// error (fail closed — a silent default would hide an unset field).
	Direction string `json:"direction"`
	// Tiers, when true, appends ` (tN)` to every resolved node's label, N read
	// from the graph node's tier. A resolved boundary pseudo-node has no tier and
	// gets no suffix.
	Tiers     bool           `json:"tiers,omitempty"`
	Nodes     []ManifestNode `json:"nodes"`
	Subgraphs []Subgraph     `json:"subgraphs,omitempty"`
	Overlays  Overlays       `json:"overlays,omitempty"`
}

// ManifestNode is one function to draw. Its identity in the diagram is ID (a
// mermaid identifier); Fn resolves it to a function in the graph named by Graph.
type ManifestNode struct {
	ID string `json:"id"`
	// Graph is the logical name (given on the CLI as <logical>=<graph.json>) of
	// the graph this node's Fn is resolved against — the axis that lets one
	// manifest span several services.
	Graph string `json:"graph"`
	// Fn is a plain normalized-FQN suffix resolved via fqnres against Graph's
	// resolution universe; it must match exactly one function. A `/regex/` form is
	// rejected (a diagram node is one node, not a set).
	Fn string `json:"fn"`
	// Label is the box text. Manifest nodes require a non-empty label (the spec
	// always sets one); an empty label is an error, fail closed.
	Label string `json:"label"`
}

// Subgraph is a mermaid subgraph box grouping some manifest nodes. Membership is
// declaration-position based, so every member is declared inside the block.
type Subgraph struct {
	ID    string   `json:"id"`
	Title string   `json:"title,omitempty"`
	Nodes []string `json:"nodes"`
}

// Overlays is the judgment layer: conceptual nodes and always-dashed proposal
// edges the human adds on top of the computed core.
type Overlays struct {
	Nodes []OverlayNode `json:"nodes,omitempty"`
	Edges []OverlayEdge `json:"edges,omitempty"`
}

// OverlayNode is a conceptual node — NEVER resolved against any graph. Shape is
// rect (default), db, or circle; only a circle may carry an empty label.
type OverlayNode struct {
	ID    string `json:"id"`
	Label string `json:"label,omitempty"`
	Shape string `json:"shape,omitempty"`
}

// OverlayEdge is an always-dashed proposal edge. Endpoints are manifest node ids
// or overlay node ids. Label is optional.
type OverlayEdge struct {
	From  string `json:"from"`
	To    string `json:"to"`
	Label string `json:"label,omitempty"`
}

// Verdict marks a diagram error that is a COMPUTED verdict failure — the overlay
// guard tripping (the graph contradicts the manifest's judgment) or a `--check`
// drift — as opposed to an operational error (bad input, unreadable file). The
// CLI maps it to groundwork's verdict exit code (1), mirroring cmdAssert's split;
// everything else exits 2.
type Verdict struct{ Msg string }

func (e Verdict) Error() string { return e.Msg }

// idPattern is the mermaid-identifier charset every manifest id (node, overlay
// node, subgraph) must match: a letter then letters/digits/underscore. Ids are
// emitted verbatim as mermaid node identifiers, so a stray '-'/'.'/space would
// produce a broken diagram — refuse at load rather than emit garbage.
var idPattern = regexp.MustCompile(`^[A-Za-z][A-Za-z0-9_]*$`)

// LoadFile reads and strictly decodes a diagram manifest. Unknown keys are
// rejected (DisallowUnknownFields) and any trailing token after the single JSON
// value is an error — the same fail-closed single-value guard graph.Load applies,
// so a manifest that is secretly two documents cannot slip through.
func LoadFile(path string) (*Manifest, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer func() { _ = f.Close() }()
	dec := json.NewDecoder(f)
	dec.DisallowUnknownFields()
	var m Manifest
	if err := dec.Decode(&m); err != nil {
		return nil, fmt.Errorf("%s: decode diagram manifest: %w", path, err)
	}
	// Exactly one JSON value (parity with graph.Load / claims.LoadFile): dec.Token()
	// must reach a clean io.EOF. dec.More() alone is insufficient — it returns false
	// when trailing bytes begin with '}' or ']'.
	if _, err := dec.Token(); err != io.EOF {
		return nil, fmt.Errorf("%s: trailing data after diagram JSON (expected a single object)", path)
	}
	return &m, nil
}

// Generate renders the manifest against the supplied graphs (keyed by their
// logical CLI name) and returns the mermaid text. It fails closed on every
// ambiguous or contradictory input; the overlay guard is the one operational-vs-
// verdict split (it returns a Verdict). The output ends with a trailing newline.
func Generate(m *Manifest, graphs map[string]*graph.Graph) (string, error) {
	dir, err := validateDirection(m.Direction)
	if err != nil {
		return "", err
	}
	if strings.TrimSpace(m.ID) == "" {
		return "", fmt.Errorf("manifest requires a non-empty id (it names the diagram in the provenance line and --check selector)")
	}

	// Per-graph models: the unique-pair set + resolution universe + tier lookup.
	models := make(map[string]*graphModel, len(graphs))
	for name, g := range graphs {
		models[name] = newGraphModel(g)
	}

	// Id registry across manifest nodes + overlay nodes + subgraphs (one namespace):
	// charset-check and reject duplicates. Registered in that order so a duplicate
	// names the first-seen id's role deterministically.
	ids := newIDRegistry()

	// Resolve every manifest node in manifest order.
	idxByID := make(map[string]int, len(m.Nodes))
	nodeFQN := make([]string, len(m.Nodes))
	nodeDecl := make([]string, len(m.Nodes))
	referenced := map[string]bool{} // logical graphs actually used by a node
	fqnSeen := map[[2]string]int{}  // (graph, fqn) -> node index, for the same-fqn guard
	for i, n := range m.Nodes {
		if err := ids.add(n.ID, "node"); err != nil {
			return "", err
		}
		if n.Label == "" {
			return "", fmt.Errorf("manifest node %q requires a non-empty label", n.ID)
		}
		gm, ok := models[n.Graph]
		if !ok {
			return "", fmt.Errorf("manifest node %q binds unknown logical graph %q (name a graph on the CLI as %s=<graph.json>)", n.ID, n.Graph, n.Graph)
		}
		referenced[n.Graph] = true
		fqn, err := gm.resolve(n.Fn)
		if err != nil {
			return "", fmt.Errorf("manifest node %q: %w", n.ID, err)
		}
		if prev, dup := fqnSeen[[2]string{n.Graph, fqn}]; dup {
			return "", fmt.Errorf("manifest nodes %q and %q both resolve to %s in graph %q — one function drawn as two ids is an ambiguous diagram", m.Nodes[prev].ID, n.ID, fqn, n.Graph)
		}
		fqnSeen[[2]string{n.Graph, fqn}] = i
		suffix, err := gm.tierSuffix(fqn, m.Tiers, n.Graph)
		if err != nil {
			return "", err
		}
		idxByID[n.ID] = i
		nodeFQN[i] = fqn
		nodeDecl[i] = n.ID + `["` + escapeLabel(n.Label+suffix) + `"]`
	}

	// A supplied graph no node references is almost certainly a typo (wrong logical
	// name, or a stale pair): refuse rather than silently ignore it (fail closed).
	// Iterate in sorted order so that when several graphs are unreferenced the NAMED
	// one — and thus the error message — is deterministic, not a map-iteration
	// artifact (the prime directive covers error text too).
	for _, name := range setutil.SortedKeys(graphs) {
		if !referenced[name] {
			return "", fmt.Errorf("supplied graph %q is referenced by no manifest node (drop it, or fix a node's graph binding)", name)
		}
	}

	// Overlay node declarations (never resolved against a graph).
	decl := make(map[string]string, len(m.Nodes)+len(m.Overlays.Nodes))
	for i := range m.Nodes {
		decl[m.Nodes[i].ID] = nodeDecl[i]
	}
	for _, on := range m.Overlays.Nodes {
		if err := ids.add(on.ID, "overlay node"); err != nil {
			return "", err
		}
		d, err := overlayNodeDecl(on)
		if err != nil {
			return "", err
		}
		decl[on.ID] = d
	}

	// Subgraphs: register ids, bind members to node indices, forbid a node in two
	// subgraphs, and reject a member that is not a manifest node id.
	sgOf := make([]string, len(m.Nodes)) // subgraph id per node index, "" if none
	for _, sg := range m.Subgraphs {
		if err := ids.add(sg.ID, "subgraph"); err != nil {
			return "", err
		}
		for _, member := range sg.Nodes {
			idx, ok := idxByID[member]
			if !ok {
				return "", fmt.Errorf("subgraph %q lists member %q which is not a manifest node id", sg.ID, member)
			}
			if sgOf[idx] != "" {
				return "", fmt.Errorf("node %q is a member of two subgraphs (%q and %q) — a node belongs to at most one", member, sgOf[idx], sg.ID)
			}
			sgOf[idx] = sg.ID
		}
	}

	// Overlay edge endpoints must reference a manifest node id or an overlay node id
	// — the two things that HAVE a bracket declaration (decl). A subgraph id is a
	// registered id but has no node declaration, so it cannot be an edge endpoint;
	// checking membership in decl (not the whole id namespace) rejects it, and an
	// unknown id, in one predicate. Validated after decl is fully built.
	for _, oe := range m.Overlays.Edges {
		if _, ok := decl[oe.From]; !ok {
			return "", fmt.Errorf("overlay edge endpoint %q (from) is not a manifest node or overlay node id", oe.From)
		}
		if _, ok := decl[oe.To]; !ok {
			return "", fmt.Errorf("overlay edge endpoint %q (to) is not a manifest node or overlay node id", oe.To)
		}
	}

	// Core edge induction: the induced subgraph over the manifest nodes.
	core := induceCore(m.Nodes, nodeFQN, models)

	// Overlay guard: an overlay edge whose endpoints both resolve to same-graph
	// manifest nodes must not restate a core edge (VERDICT).
	if err := overlayGuard(m.Overlays.Edges, idxByID, m.Nodes, nodeFQN, models); err != nil {
		return "", err
	}

	stamps := stampsLine(graphs)
	return emit(m, dir, stamps, decl, idxByID, sgOf, core), nil
}

// validateDirection returns the direction or an error. Empty/missing is an error
// (fail closed) — a silent default would ratify an unset field.
func validateDirection(d string) (string, error) {
	switch d {
	case "LR", "RL", "TB", "BT", "TD":
		return d, nil
	case "":
		return "", fmt.Errorf("manifest requires a direction (one of LR, RL, TB, BT, TD)")
	default:
		return "", fmt.Errorf("invalid direction %q (want one of LR, RL, TB, BT, TD)", d)
	}
}

// coreEdge is an induced solid edge between two manifest nodes, by node index.
type coreEdge struct{ from, to int }

// induceCore returns the induced subgraph over the manifest nodes: for every
// ordered pair of node indices (a, b) — self-pairs (a, a) included, so a genuine
// recursive self-call is drawn — a→b is a core edge iff both nodes are bound to
// the SAME logical graph and (fqn(a), fqn(b)) is in that graph's unique-pair set.
// Cross-graph pairs are never drawn. Iterating a then b makes the raw list
// deterministic; the emitter re-sorts by (from, to) index regardless.
func induceCore(nodes []ManifestNode, nodeFQN []string, models map[string]*graphModel) []coreEdge {
	var core []coreEdge
	for a := range nodes {
		for b := range nodes {
			if nodes[a].Graph != nodes[b].Graph {
				continue
			}
			gm := models[nodes[a].Graph]
			if gm.pairs[[2]string{nodeFQN[a], nodeFQN[b]}] {
				core = append(core, coreEdge{a, b})
			}
		}
	}
	return core
}

// overlayGuard refuses an overlay edge that restates a core edge: judgment may
// never dash-draw a fact the solid layer already computed. It fires ONLY when
// both endpoints are manifest nodes bound to the same graph and their (fqn, fqn)
// pair exists there; an overlay-node endpoint or a cross-graph span is exempt (it
// cannot be a single-graph core edge). The violation is a Verdict (exit 1): the
// graph now contradicts the manifest's declared judgment.
func overlayGuard(edges []OverlayEdge, idxByID map[string]int, nodes []ManifestNode, nodeFQN []string, models map[string]*graphModel) error {
	for _, oe := range edges {
		fa, okA := idxByID[oe.From]
		fb, okB := idxByID[oe.To]
		if !okA || !okB {
			continue // touches an overlay node — exempt
		}
		if nodes[fa].Graph != nodes[fb].Graph {
			continue // spans two graphs — cannot be a single-graph core edge
		}
		gm := models[nodes[fa].Graph]
		if gm.pairs[[2]string{nodeFQN[fa], nodeFQN[fb]}] {
			return Verdict{Msg: fmt.Sprintf(
				"overlay edge %s -.-> %s restates a core edge: %s -> %s exists in graph %q, so it belongs to the computed layer, not the judgment overlay",
				oe.From, oe.To, nodeFQN[fa], nodeFQN[fb], nodes[fa].Graph)}
		}
	}
	return nil
}

// stampsLine is the provenance stamp: the sorted, unique, non-empty `tool` values
// of the input graphs joined by ", ", or the literal "unstamped" when none carry
// one (the committed goldens strip `tool`). Routes through setutil.SortedKeys, the
// codebase's single ordering primitive, so it cannot leak map-iteration order.
func stampsLine(graphs map[string]*graph.Graph) string {
	set := map[string]bool{}
	for _, g := range graphs {
		if g.Tool != "" {
			set[g.Tool] = true
		}
	}
	if len(set) == 0 {
		return "unstamped"
	}
	return strings.Join(setutil.SortedKeys(set), ", ")
}

// idRegistry enforces the single manifest-id namespace: node ids, overlay node
// ids, and subgraph ids share it, each must be a mermaid identifier, and no two
// may collide.
type idRegistry struct{ kind map[string]string }

func newIDRegistry() *idRegistry { return &idRegistry{kind: map[string]string{}} }

func (r *idRegistry) add(id, kind string) error {
	if !idPattern.MatchString(id) {
		return fmt.Errorf("%s id %q is not a valid mermaid identifier (want %s)", kind, id, idPattern.String())
	}
	if prev, dup := r.kind[id]; dup {
		return fmt.Errorf("duplicate id %q (used by a %s and a %s) — node/overlay/subgraph ids share one namespace", id, prev, kind)
	}
	r.kind[id] = kind
	return nil
}

// graphModel is the once-per-graph view generation shares: the unique-pair set
// (core-edge membership), the resolution universe (fqnres input), and the per-FQN
// tier lookup (label annotation). It is a pure function of the graph's content —
// node/edge arrival order does not affect any field.
type graphModel struct {
	pairs    map[[2]string]bool
	universe []string
	// tiers maps a NODE FQN to its sorted distinct tiers. A boundary pseudo-node
	// (edge endpoint, not a Node) is absent here — genuinely tier-less. graph.Load
	// does not guarantee node-FQN uniqueness (a generic instance's display FQN is
	// non-unique), so an FQN can carry more than one tier; tierSuffix abstains on
	// that rather than annotate an arbitrary one.
	tiers map[string][]int
}

func newGraphModel(g *graph.Graph) *graphModel {
	pairs := make(map[[2]string]bool, len(g.Edges))
	for _, e := range g.Edges {
		pairs[[2]string{e.From, e.To}] = true
	}
	tierSet := make(map[string]map[int]bool, len(g.Nodes))
	for _, n := range g.Nodes {
		if tierSet[n.FQN] == nil {
			tierSet[n.FQN] = map[int]bool{}
		}
		tierSet[n.FQN][n.Tier] = true
	}
	tiers := make(map[string][]int, len(tierSet))
	for fqn, set := range tierSet {
		vs := make([]int, 0, len(set))
		for v := range set {
			vs = append(vs, v)
		}
		sort.Ints(vs)
		tiers[fqn] = vs
	}
	return &graphModel{
		pairs:    pairs,
		universe: claims.EndpointUniverse(g), // node FQNs ∪ edge endpoints — one source of truth
		tiers:    tiers,
	}
}

// resolve maps a manifest node's plain `fn` to exactly one FQN via fqnres. A
// regex form is refused (a diagram node names one function, so multi-match is not
// meaningful — fail closed). Zero matches → UNRESOLVED, two or more → AMBIGUOUS,
// both using fqnres' shared report wording so the message reads identically to
// `groundwork assert`.
func (gm *graphModel) resolve(fn string) (string, error) {
	if strings.TrimSpace(fn) == "" {
		return "", fmt.Errorf("requires a non-empty fn")
	}
	if fqnres.IsRegex(fn) {
		return "", fmt.Errorf("fn %s is a /regex/ form, which is not meaningful for a diagram node (a node names exactly one function); use a plain normalized-FQN suffix", fqnres.QuoteSingle(fn))
	}
	res, err := fqnres.Resolve(fn, gm.universe)
	if err != nil {
		return "", err // a plain query never errors, but surface it if it ever does
	}
	if len(res.Matches) == 0 {
		return "", fmt.Errorf("%s", fqnres.UnresolvedDetail(fn, "node/endpoint"))
	}
	if len(res.Matches) > 1 {
		return "", fmt.Errorf("%s", fqnres.AmbiguousDetail(fn, res.Matches))
	}
	return res.Matches[0], nil
}

// tierSuffix returns the ` (tN)` label suffix for a resolved node under tiers, or
// "" when tiers is off or the FQN is a boundary pseudo-node (no tier — honest
// omission). A node the graph carries at more than one tier is unanswerable, so
// it abstains with an error rather than annotate an arbitrary tier (fail closed).
func (gm *graphModel) tierSuffix(fqn string, tiers bool, graphName string) (string, error) {
	if !tiers {
		return "", nil
	}
	ts, ok := gm.tiers[fqn]
	if !ok {
		return "", nil // boundary pseudo-endpoint — genuinely tier-less
	}
	if len(ts) > 1 {
		return "", fmt.Errorf("node %s carries tiers %v in graph %q — tier annotation is ambiguous; abstaining", fqn, ts, graphName)
	}
	return fmt.Sprintf(" (t%d)", ts[0]), nil
}
