package diagram

import (
	"sort"
	"strings"
)

// escapeLabel makes a label safe inside mermaid double quotes. The ONE escape is
// an embedded `"` → `&quot;` (mermaid's entity form): a deterministic total
// function, so a label is never rejected for its content and never renders an
// unbalanced quote. No other character is touched — mermaid tolerates `|`, `(`,
// `[`, etc. inside a quoted label.
func escapeLabel(s string) string {
	return strings.ReplaceAll(s, `"`, "&quot;")
}

// overlayNodeDecl renders an overlay node's one-and-only bracket declaration per
// its shape: rect → `id["…"]`, db → `id[("…")]`, circle → `id(("…"))`. An empty
// label is legal ONLY with circle (renders `id(( ))`); rect/db with an empty
// label, or an unknown shape, is an error (fail closed on an authoring slip).
func overlayNodeDecl(on OverlayNode) (string, error) {
	esc := escapeLabel(on.Label)
	switch on.Shape {
	case "", "rect":
		if on.Label == "" {
			return "", overlayEmptyLabelErr(on.ID, on.Shape)
		}
		return on.ID + `["` + esc + `"]`, nil
	case "db":
		if on.Label == "" {
			return "", overlayEmptyLabelErr(on.ID, on.Shape)
		}
		return on.ID + `[("` + esc + `")]`, nil
	case "circle":
		if on.Label == "" {
			return on.ID + "(( ))", nil
		}
		return on.ID + `(("` + esc + `"))`, nil
	default:
		return "", overlayShapeErr(on.ID, on.Shape)
	}
}

func overlayEmptyLabelErr(id, shape string) error {
	s := shape
	if s == "" {
		s = "rect"
	}
	return &shapeError{msg: "overlay node " + quote(id) + " has an empty label but shape " + quote(s) + "; only a circle may be empty"}
}

func overlayShapeErr(id, shape string) error {
	return &shapeError{msg: "overlay node " + quote(id) + " has unknown shape " + quote(shape) + " (want rect, db, or circle)"}
}

// shapeError is a tiny typed error so the two overlay-node schema failures read
// with a stable message; it is operational (exit 2), never a Verdict.
type shapeError struct{ msg string }

func (e *shapeError) Error() string { return e.msg }

func quote(s string) string { return `"` + s + `"` }

// emitter tracks which ids have had their bracket declaration emitted. ref
// returns the full declaration at first mention and the bare id thereafter, so
// each node is declared EXACTLY once (mermaid rule: a second bracket form for the
// same id is a redefinition).
type emitter struct {
	b        strings.Builder
	declared map[string]bool
	decl     map[string]string
}

func (e *emitter) ref(id string) string {
	if e.declared[id] {
		return id
	}
	e.declared[id] = true
	return e.decl[id]
}

// emit renders the mermaid document in the fixed, deterministic order documented
// on the package. decl maps every node id (manifest + overlay) to its bracket
// declaration; sgOf gives each manifest node's subgraph id (or ""). All ordering
// is manifest order or a sort on intrinsic (from index, to index).
func emit(m *Manifest, dir, stamps string, decl map[string]string, idxByID map[string]int, sgOf []string, core []coreEdge) string {
	e := &emitter{declared: map[string]bool{}, decl: decl}
	e.b.WriteString("flowchart " + dir + "\n")
	e.b.WriteString("    %% generated by gen-diagram from " + m.ID + "/diagram.json @ " + stamps + " — do not hand-edit the core\n")

	// (1) Subgraph blocks, in manifest order. Each block declares all its members
	// INSIDE it (mermaid membership is declaration-position based): first the
	// intra-subgraph core edges (both endpoints members), then any member not yet
	// declared, standalone — both in the deterministic orders below.
	for _, sg := range m.Subgraphs {
		if sg.Title == "" {
			e.b.WriteString("    subgraph " + sg.ID + "\n")
		} else {
			e.b.WriteString("    subgraph " + sg.ID + `["` + escapeLabel(sg.Title) + `"]` + "\n")
		}
		for _, ce := range intraSorted(core, sgOf, sg.ID) {
			e.b.WriteString("        " + e.ref(m.Nodes[ce.from].ID) + " --> " + e.ref(m.Nodes[ce.to].ID) + "\n")
		}
		// Undeclared members, in global manifest-node order (the same "manifest
		// order" every standalone pass below uses), so the block's tail is stable.
		for idx := range m.Nodes {
			if sgOf[idx] != sg.ID || e.declared[m.Nodes[idx].ID] {
				continue
			}
			e.b.WriteString("        " + e.ref(m.Nodes[idx].ID) + "\n")
		}
		e.b.WriteString("    end\n")
	}

	// (2) Remaining core edges — at least one endpoint outside a subgraph, or the
	// two in different subgraphs — sorted by (from index, to index). Every
	// subgraph member is already declared (step 1), so a member reference here is
	// bare; a non-member is declared at first mention.
	for _, ce := range remainingSorted(core, sgOf) {
		e.b.WriteString("    " + e.ref(m.Nodes[ce.from].ID) + " --> " + e.ref(m.Nodes[ce.to].ID) + "\n")
	}

	// (3) Never-referenced manifest nodes — touched by no core edge and in no
	// subgraph — standalone, manifest order. Anything reached in step 1/2 is
	// already declared and skipped.
	touched := touchedNodes(core)
	for idx := range m.Nodes {
		if touched[idx] || sgOf[idx] != "" || e.declared[m.Nodes[idx].ID] {
			continue
		}
		e.b.WriteString("    " + e.ref(m.Nodes[idx].ID) + "\n")
	}

	// (4) Overlay edges, manifest order — ALWAYS dashed, optional label. ref(From)
	// is taken before ref(To) so the left endpoint is declared first.
	for _, oe := range m.Overlays.Edges {
		from := e.ref(oe.From)
		to := e.ref(oe.To)
		if oe.Label == "" {
			e.b.WriteString("    " + from + " -.-> " + to + "\n")
		} else {
			e.b.WriteString("    " + from + ` -.->|"` + escapeLabel(oe.Label) + `"| ` + to + "\n")
		}
	}

	// (5) Overlay nodes not touched by any overlay edge — standalone, manifest order.
	refd := overlayEndpointSet(m.Overlays.Edges)
	for _, on := range m.Overlays.Nodes {
		if refd[on.ID] {
			continue
		}
		e.b.WriteString("    " + e.ref(on.ID) + "\n")
	}

	return e.b.String()
}

// intraSorted returns the core edges whose BOTH endpoints are members of subgraph
// sgID, sorted by (from index, to index).
func intraSorted(core []coreEdge, sgOf []string, sgID string) []coreEdge {
	var out []coreEdge
	for _, ce := range core {
		if sgOf[ce.from] == sgID && sgOf[ce.to] == sgID {
			out = append(out, ce)
		}
	}
	sortEdges(out)
	return out
}

// remainingSorted returns the core edges that are NOT intra-subgraph (a member
// pair in the same block), sorted by (from index, to index).
func remainingSorted(core []coreEdge, sgOf []string) []coreEdge {
	var out []coreEdge
	for _, ce := range core {
		if sgOf[ce.from] != "" && sgOf[ce.from] == sgOf[ce.to] {
			continue // intra — emitted inside the block
		}
		out = append(out, ce)
	}
	sortEdges(out)
	return out
}

// sortEdges orders edges by (from index, to index) — the intrinsic, run-
// independent key, so the emission cannot depend on induction order.
func sortEdges(es []coreEdge) {
	sort.Slice(es, func(i, j int) bool {
		if es[i].from != es[j].from {
			return es[i].from < es[j].from
		}
		return es[i].to < es[j].to
	})
}

func touchedNodes(core []coreEdge) map[int]bool {
	out := map[int]bool{}
	for _, ce := range core {
		out[ce.from] = true
		out[ce.to] = true
	}
	return out
}

func overlayEndpointSet(edges []OverlayEdge) map[string]bool {
	out := map[string]bool{}
	for _, oe := range edges {
		out[oe.From] = true
		out[oe.To] = true
	}
	return out
}
